/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

/**
 *
 * @author ASUS
 */
public class Kalkulator1 extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator1
     */
    public Kalkulator1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_bilangan1 = new javax.swing.JTextField();
        tf_bilangan2 = new javax.swing.JTextField();
        Bilangan1 = new javax.swing.JLabel();
        Bilangan2 = new javax.swing.JLabel();
        kabataku = new javax.swing.JComboBox<>();
        btn_hitung = new javax.swing.JButton();
        Jawaban = new javax.swing.JLabel();
        Hasilnya = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel1.setText("Kalkulator");

        Bilangan1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Bilangan1.setText("Bilangan 1");

        Bilangan2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Bilangan2.setText("Bilangan 2");

        kabataku.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kabataku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perkalian", "Pembagian", "Penjumlahan", "Pengurangan" }));
        kabataku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kabatakuActionPerformed(evt);
            }
        });

        btn_hitung.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_hitung.setText("Hitung");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        Jawaban.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Jawaban.setText("Hasilnya");

        Hasilnya.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jawaban)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bilangan2)
                            .addComponent(Bilangan1)
                            .addComponent(tf_bilangan2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_bilangan1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hasilnya, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btn_hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(kabataku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(Bilangan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_bilangan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bilangan2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_bilangan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kabataku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jawaban)
                .addGap(1, 1, 1)
                .addComponent(Hasilnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btn_hitung)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kabatakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kabatakuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kabatakuActionPerformed

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        // TODO add your handling code here:
        if (kabataku.getSelectedItem().toString().equalsIgnoreCase("Perkalian")){
   int a=Integer.parseInt(tf_bilangan1.getText());
   int b=Integer.parseInt(tf_bilangan2.getText());
   int jumlah=a*b;
   Hasilnya.setText (Integer.toString (jumlah));   
}
if (kabataku.getSelectedItem().toString().equalsIgnoreCase("Pembagian")){
     int a=Integer.parseInt(tf_bilangan1.getText());
   int b=Integer.parseInt(tf_bilangan2.getText());
   int jumlah=a/b;
  Hasilnya.setText (Integer.toString (jumlah));   
}
if (kabataku.getSelectedItem().toString().equalsIgnoreCase("Penjumlahan")){
    int a=Integer.parseInt(tf_bilangan1.getText());
   int b=Integer.parseInt(tf_bilangan2.getText());
   int jumlah=a+b;
   Hasilnya.setText (Integer.toString (jumlah));   
}
if (kabataku.getSelectedItem().toString().equalsIgnoreCase("Pengurangan")){
  int a=Integer.parseInt(tf_bilangan1.getText());
   int b=Integer.parseInt(tf_bilangan2.getText());
   int jumlah=a-b;
   Hasilnya.setText (Integer.toString (jumlah));   
}
    }//GEN-LAST:event_btn_hitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bilangan1;
    private javax.swing.JLabel Bilangan2;
    private javax.swing.JTextField Hasilnya;
    private javax.swing.JLabel Jawaban;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> kabataku;
    private javax.swing.JTextField tf_bilangan1;
    private javax.swing.JTextField tf_bilangan2;
    // End of variables declaration//GEN-END:variables
}
